name: amar_recipe_admin
description: Amar Recipe V2 Admin Panel
publish_to: "none"
version: 2.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
