import 'package:flutter/material.dart';
void main()=>runApp(const A());
class A extends StatelessWidget{const A({super.key});Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Amar Recipe Admin',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:const Login());}
class Login extends StatefulWidget{const Login({super.key});State<Login> createState()=>_L();}
class _L extends State<Login>{final e=TextEditingController(),p=TextEditingController();String err='';
Widget build(BuildContext c)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Padding(padding:const EdgeInsets.all(24),child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.admin_panel_settings,size:70),const Text('Amar Recipe Admin',style:TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const SizedBox(height:20),TextField(controller:e,decoration:const InputDecoration(labelText:'Admin Email',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Password',border:OutlineInputBorder())),Text(err,style:const TextStyle(color:Colors.red)),FilledButton(onPressed:(){if(e.text=='admin@example.com'&&p.text=='admin123')Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const Dash()));else setState(()=>err='ভুল ইমেইল/পাসওয়ার্ড');},child:const Text('Login')),const Text('Demo: admin@example.com / admin123')]))))));}}
class Item{String n,c,co,img,t,d;Item(this.n,this.c,this.co,this.img,this.t,this.d);}
final items=[Item('চিকেন বিরিয়ানি','ভাত','বাংলাদেশ','https://images.unsplash.com/photo-1563379091339-03246963d96c?w=900','60 মিনিট','সুগন্ধি বিরিয়ানি'),Item('ইলিশ ভাজা','মাছ','বাংলাদেশ','https://images.unsplash.com/photo-1547592180-85f173990554?w=900','25 মিনিট','মচমচে ইলিশ')];
class Dash extends StatefulWidget{const Dash({super.key});State<Dash> createState()=>_Dash();}
class _Dash extends State<Dash>{int s=0;Widget build(BuildContext c){final ps=[recipes(),categories(),const Center(child:Text('Settings'))];return Scaffold(appBar:AppBar(title:const Text('Amar Recipe Admin')),drawer:Drawer(child:ListView(children:[const DrawerHeader(child:Text('Admin Panel',style:TextStyle(fontSize:25))),ListTile(title:const Text('Recipes'),onTap:(){setState(()=>s=0);Navigator.pop(c);}),ListTile(title:const Text('Categories'),onTap:(){setState(()=>s=1);Navigator.pop(c);}),ListTile(title:const Text('Settings'),onTap:(){setState(()=>s=2);Navigator.pop(c);})])),body:ps[s]);}
Widget recipes()=>ListView(padding:const EdgeInsets.all(16),children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Recipes',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('Add'))]),...items.asMap().entries.map((x)=>Card(child:ListTile(leading:CircleAvatar(backgroundImage:NetworkImage(x.value.img)),title:Text(x.value.n),subtitle:Text('${x.value.co} • ${x.value.c} • ${x.value.t}'),trailing:Wrap(children:[IconButton(onPressed:()=>edit(x.key),icon:const Icon(Icons.edit)),IconButton(onPressed:()=>setState(()=>items.removeAt(x.key)),icon:const Icon(Icons.delete))])))]); 
Widget categories()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Categories',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),...['ভাত','মাছ','মাংস','সবজি','ডাল','ভর্তা','নুডলস','পাস্তা','মিষ্টি','পানীয়'].map((x)=>ListTile(title:Text(x),trailing:const Icon(Icons.edit)))]);
void add()=>form();void edit(int i)=>form(i,items[i]);
void form([int? i,Item? old]){final n=TextEditingController(text:old?.n??''),c=TextEditingController(text:old?.c??''),co=TextEditingController(text:old?.co??'বাংলাদেশ'),img=TextEditingController(text:old?.img??''),t=TextEditingController(text:old?.t??''),d=TextEditingController(text:old?.d??'');showDialog(context:context,builder:(x)=>AlertDialog(title:Text(i==null?'Add Recipe':'Edit Recipe'),content:SizedBox(width:420,child:SingleChildScrollView(child:Column(children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:c,decoration:const InputDecoration(labelText:'Category')),TextField(controller:co,decoration:const InputDecoration(labelText:'Country')),TextField(controller:img,decoration:const InputDecoration(labelText:'Image URL')),TextField(controller:t,decoration:const InputDecoration(labelText:'Time')),TextField(controller:d,decoration:const InputDecoration(labelText:'Description'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Cancel')),FilledButton(onPressed:(){final z=Item(n.text,c.text,co.text,img.text,t.text,d.text);setState(()=>i==null?items.add(z):items[i!]=z);Navigator.pop(x);},child:const Text('Save'))]));}
}
